name: Release Bundles

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true
        type: string
      release_name:
        description: 'Release name'
        required: false
        type: string
      release_notes:
        description: 'Release notes'
        required: false
        type: string
        default: 'OpenDSU SDK bundle release'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout SDK code
        uses: actions/checkout@v3
        with:
          path: opendsu-sdk
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: opendsu-sdk
        run: npm run dev-install
      
      - name: Build bundles
        working-directory: opendsu-sdk
        run: npm run build
      
      - name: Checkout releases repository
        uses: actions/checkout@v3
        with:
          repository: OpenDSU/opendsu-releases
          token: ${{ secrets.GIT_TOKEN }}
          path: opendsu-releases
      
      - name: Create release structure
        run: |
          # Clean up existing files (preserve .git directory)
          find opendsu-releases -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +
          
          # Create directories for the new release
          mkdir -p opendsu-releases/builds/output
          mkdir -p opendsu-releases/psknode/bin/scripts
          mkdir -p opendsu-releases/conf
      
      - name: Copy bundle files to releases repo
        run: |
          # Copy all browserify bundles to builds/output directory
          cp -r opendsu-sdk/builds/output/* opendsu-releases/builds/output/
          
          # Copy launcher scripts to psknode/bin/scripts directory
          cp opendsu-sdk/psknode/bin/scripts/apiHubLauncher.js opendsu-releases/psknode/bin/scripts/
          cp opendsu-sdk/psknode/bin/scripts/enclaveLauncher.js opendsu-releases/psknode/bin/scripts/
          
          # No need to update paths - keeping the same structure as original
          
          # Create minimal package.json for release
          cat > opendsu-releases/package.json << 'EOF'
          {
            "name": "opendsu-sdk-release",
            "version": "${{ github.event.inputs.tag_name }}",
            "description": "OpenDSU SDK Bundle Release",
            "scripts": {
              "start": "node ./psknode/bin/scripts/apiHubLauncher.js",
              "cloud-enclave": "node ./psknode/bin/scripts/enclaveLauncher.js",
              "remote-enclave": "npm run cloud-enclave"
            },
            "dependencies": {}
          }
          EOF
          
          # Copy default conf directory if exists
          if [ -d "opendsu-sdk/conf" ]; then
            cp -r opendsu-sdk/conf/* opendsu-releases/conf/ 2>/dev/null || true
          fi
          
          # Create version info file
          echo "${{ github.event.inputs.tag_name }}" > opendsu-releases/VERSION
          echo "Built on: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> opendsu-releases/VERSION
          echo "Source commit: ${{ github.sha }}" >> opendsu-releases/VERSION
      
      - name: Create README for releases repo
        run: |
          cat > opendsu-releases/README.md << 'EOF'
          # OpenDSU Releases
          
          This repository contains pre-built bundles for the OpenDSU SDK.
          
          ## Current Release
          
          - Version: ${{ github.event.inputs.tag_name }}
          - Build Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
          - Source: [OpenDSU/opendsu-sdk](https://github.com/OpenDSU/opendsu-sdk) commit ${{ github.sha }}
          
          ## Usage
          
          ### Clone and run
          
          ```bash
          git clone https://github.com/OpenDSU/opendsu-releases.git
          cd opendsu-releases
          npm run start
          ```
          
          ### Download specific version
          
          Use git tags to checkout a specific version:
          
          ```bash
          git clone https://github.com/OpenDSU/opendsu-releases.git
          cd opendsu-releases
          git checkout <tag_name>
          npm run start
          ```
          
          ## Contents
          
          This repository contains:
          - Pre-built browserify bundles in `builds/output/`
          - Launcher scripts in `psknode/bin/scripts/`
          - Minimal package.json with start scripts
          - Configuration files (if applicable)
          
          ## Available Scripts
          
          - `npm run start` - Launch the API Hub
          - `npm run cloud-enclave` - Launch cloud enclave
          - `npm run remote-enclave` - Launch remote enclave
          
          ## Source
          
          These bundles are built from [OpenDSU/opendsu-sdk](https://github.com/OpenDSU/opendsu-sdk)
          EOF
      
      - name: Commit and push to releases repo
        working-directory: opendsu-releases
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Determine the default branch (try multiple methods)
          if git show-ref --verify --quiet refs/remotes/origin/master; then
            DEFAULT_BRANCH="master"
          elif git show-ref --verify --quiet refs/remotes/origin/main; then
            DEFAULT_BRANCH="main"
          else
            # Fallback: get the current branch
            DEFAULT_BRANCH=$(git branch --show-current)
          fi
          
          echo "Detected default branch: ${DEFAULT_BRANCH}"
          
          # Add all changes
          git add -A
          
          # Commit with release information
          git commit -m "Release ${{ github.event.inputs.tag_name }}
          
          Built from opendsu-sdk commit: ${{ github.sha }}
          Release notes: ${{ github.event.inputs.release_notes }}"
          
          # Create and push tag
          git tag -a "${{ github.event.inputs.tag_name }}" -m "Release ${{ github.event.inputs.tag_name }}"
          
          # Push commits and tags to the releases repository
          git push origin HEAD:${DEFAULT_BRANCH}
          git push origin "${{ github.event.inputs.tag_name }}"
      
      - name: Create GitHub Release in releases repo
        working-directory: opendsu-releases
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          # Create release using GitHub CLI
          gh release create "${{ github.event.inputs.tag_name }}" \
            --repo "OpenDSU/opendsu-releases" \
            --title "${{ github.event.inputs.release_name || github.event.inputs.tag_name }}" \
            --notes "$(cat <<'EOF'
          ${{ github.event.inputs.release_notes }}
          
          ## Contents
          This release contains:
          - Pre-built browserify bundles in \`builds/output/\`
          - Launcher scripts in \`psknode/bin/scripts/\` for \`npm run start\`
          - Minimal package.json with start scripts
          - Configuration files (if applicable)
          
          ## Usage
          
          ### Clone and run this version
          \`\`\`bash
          git clone https://github.com/OpenDSU/opendsu-releases.git --branch ${{ github.event.inputs.tag_name }}
          cd opendsu-releases
          npm run start
          \`\`\`
          
          ### Or checkout this specific version
          \`\`\`bash
          git clone https://github.com/OpenDSU/opendsu-releases.git
          cd opendsu-releases
          git checkout ${{ github.event.inputs.tag_name }}
          npm run start
          \`\`\`
          
          ## Source
          Built from [OpenDSU/opendsu-sdk](https://github.com/OpenDSU/opendsu-sdk) commit: ${{ github.sha }}
          EOF
          )"